// <auto-generated />
using System;
using MCFL.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCFL.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:Backend/MCFL.API/Migrations/20260423235014_UpdatedSchemaForLoginIdentityFramework.Designer.cs
    [Migration("20260423235014_UpdatedSchemaForLoginIdentityFramework")]
    partial class UpdatedSchemaForLoginIdentityFramework
========
    [Migration("20260423213619_InitialSchemaAndSeed")]
    partial class InitialSchemaAndSeed
>>>>>>>> 7811550f4cfe12196bc2c05ee84982b2a7d73936:Backend/MCFL.API/Migrations/20260423213619_InitialSchemaAndSeed.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("MCFL.API.Models.CashInCategory", b =>
                {
                    b.Property<int>("CashInCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkCashInCategoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sortOrder");

                    b.HasKey("CashInCategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("CashInCategory");
                });

            modelBuilder.Entity("MCFL.API.Models.CashOutCategory", b =>
                {
                    b.Property<int>("CashOutCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkCashOutCategoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sortOrder");

                    b.HasKey("CashOutCategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("CashOutCategory");
                });

            modelBuilder.Entity("MCFL.API.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("onboardingCompleted");

                    b.Property<bool>("ParentConsentReceived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parentConsentReceived");

                    b.Property<bool>("ParentConsentRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parentConsentRequired");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MCFL.API.Models.LearningSavingsGoal", b =>
                {
                    b.Property<int>("LearningSavingsGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkLearningSavingsGoalId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<decimal?>("CurrentSavedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("currentSavedAmount");

                    b.Property<string>("GoalTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("goalTitle");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("targetAmount");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("targetDate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("LearningSavingsGoalId");

                    b.HasIndex("UserId");

                    b.ToTable("LearningSavingsGoal", t =>
                        {
                            t.HasCheckConstraint("CK_SavingsGoal_Amounts", "targetAmount >= 0 AND currentSavedAmount >= 0");
                        });
                });

            modelBuilder.Entity("MCFL.API.Models.LearningTopic", b =>
                {
                    b.Property<int>("LearningTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkLearningTopicId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sortOrder");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("topicName");

                    b.HasKey("LearningTopicId");

                    b.HasIndex("TopicName")
                        .IsUnique();

                    b.ToTable("LearningTopic");
                });

            modelBuilder.Entity("MCFL.API.Models.MoneyEntry", b =>
                {
                    b.Property<int>("MoneyEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkMoneyEntryId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<int?>("CashInCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkCashInCategoryId");

                    b.Property<int?>("CashOutCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkCashOutCategoryId");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("entryType");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("MoneyEntryId");

                    b.HasIndex("CashInCategoryId");

                    b.HasIndex("CashOutCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("MoneyEntry");
                });

            modelBuilder.Entity("MCFL.API.Models.MoneyFeelingSubmission", b =>
                {
                    b.Property<int>("MoneyFeelingSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkMoneyFeelingSubmissionId");

                    b.Property<string>("Feeling")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("feeling");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("submittedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("MoneyFeelingSubmissionId");

                    b.HasIndex("UserId");

                    b.ToTable("MoneyFeelingSubmission");
                });

            modelBuilder.Entity("MCFL.API.Models.ParentAccessLink", b =>
                {
                    b.Property<int>("ParentAccessLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkParentAccessLinkId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiresAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("ParentAccessLinkId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ParentAccessLink");
                });

            modelBuilder.Entity("MCFL.API.Models.ParentConsent", b =>
                {
                    b.Property<int>("ParentConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkParentConsentId");

                    b.Property<DateTime?>("ConfirmationSentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmationSentAt");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consentGiven");

                    b.Property<DateTime?>("ConsentGivenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consentGivenAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("parentEmail");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("parentName");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("ParentConsentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ParentConsent");
                });

            modelBuilder.Entity("MCFL.API.Models.ParentFeedback", b =>
                {
                    b.Property<int>("ParentFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkParentFeedbackId");

                    b.Property<string>("MoneyStory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("moneyStory");

                    b.Property<int>("ParentAccessLinkId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkParentAccessLinkId");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("parentEmail");

                    b.Property<string>("ParentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("parentName");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("submittedAt");

                    b.Property<string>("WhatChildShouldLearn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("whatChildShouldLearn");

                    b.HasKey("ParentFeedbackId");

                    b.HasIndex("ParentAccessLinkId");

                    b.ToTable("ParentFeedback");
                });

            modelBuilder.Entity("MCFL.API.Models.RegistrationAllowList", b =>
                {
                    b.Property<int>("RegistrationAllowListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkRegistrationAllowListId");

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationAllowListId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("RegistrationAllowList");
                });

<<<<<<<< HEAD:Backend/MCFL.API/Migrations/20260423235014_UpdatedSchemaForLoginIdentityFramework.Designer.cs
            modelBuilder.Entity("MCFL.API.Models.SavingsGoal", b =>
                {
                    b.Property<int>("SavingsGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkSavingsGoalId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<decimal?>("CurrentSavedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("currentSavedAmount");

                    b.Property<string>("GoalTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("goalTitle");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("targetAmount");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("targetDate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("SavingsGoalId");

                    b.HasIndex("UserId");

                    b.ToTable("SavingsGoal");
                });

========
>>>>>>>> 7811550f4cfe12196bc2c05ee84982b2a7d73936:Backend/MCFL.API/Migrations/20260423213619_InitialSchemaAndSeed.Designer.cs
            modelBuilder.Entity("MCFL.API.Models.Scenario", b =>
                {
                    b.Property<int>("ScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkScenarioId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.HasKey("ScenarioId");

                    b.ToTable("Scenario");
                });

            modelBuilder.Entity("MCFL.API.Models.ScenarioChoice", b =>
                {
                    b.Property<int>("ScenarioChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkScenarioChoiceId");

                    b.Property<int>("ConfidenceImpact")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confidenceImpact");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<string>("LessonText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lessonText");

                    b.Property<decimal>("MoneyImpact")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("moneyImpact");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("optionText");

                    b.Property<string>("ResultText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resultText");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkScenarioId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sortOrder");

                    b.HasKey("ScenarioChoiceId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioChoice");
                });

            modelBuilder.Entity("MCFL.API.Models.ScenarioPlay", b =>
                {
                    b.Property<int>("ScenarioPlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkScenarioPlayId");

                    b.Property<int>("ConfidenceAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confidenceAfter");

                    b.Property<int>("ConfidenceBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confidenceBefore");

                    b.Property<int>("ConfidenceImpactSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confidenceImpactSnapshot");

                    b.Property<decimal>("GameMoneyAfter")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("gameMoneyAfter");

                    b.Property<decimal>("GameMoneyBefore")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("gameMoneyBefore");

                    b.Property<string>("LessonTextSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lessonTextSnapshot");

                    b.Property<decimal>("MoneyImpactSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("moneyImpactSnapshot");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("playedAt");

                    b.Property<int>("ScenarioChoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkScenarioChoiceId");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkScenarioId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("ScenarioPlayId");

                    b.HasIndex("ScenarioChoiceId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("UserId");

                    b.ToTable("ScenarioPlay");
                });

            modelBuilder.Entity("MCFL.API.Models.UserFeedback", b =>
                {
                    b.Property<int>("UserFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkUserFeedbackId");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("feedbackType");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("submittedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("UserFeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeedback");
                });

            modelBuilder.Entity("MCFL.API.Models.UserGameStat", b =>
                {
                    b.Property<int>("UserGameStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkUserGameStatId");

                    b.Property<int>("CurrentConfidenceScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currentConfidenceScore");

                    b.Property<decimal>("CurrentGameMoney")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("currentGameMoney");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("UserGameStatId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserGameStat");
                });

            modelBuilder.Entity("MCFL.API.Models.UserLearningPreference", b =>
                {
                    b.Property<int>("UserLearningPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkUserLearningPreferenceId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<int>("LearningTopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkLearningTopicId");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkUserProfileId");

                    b.HasKey("UserLearningPreferenceId");

                    b.HasIndex("LearningTopicId");

                    b.HasIndex("UserProfileId", "LearningTopicId")
                        .IsUnique();

                    b.ToTable("UserLearningPreference");
                });

            modelBuilder.Entity("MCFL.API.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkUserProfileId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("EarnsMoneyAnswer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("earnsMoneyAnswer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fullName");

                    b.Property<bool>("HasBankAccount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hasBankAccount");

                    b.Property<string>("HasSavingsAnswer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("hasSavingsAnswer");

                    b.Property<string>("LearningComments")
                        .HasColumnType("TEXT")
                        .HasColumnName("learningComments");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickName");

                    b.Property<string>("ParentTeachingsAnswer")
                        .HasColumnType("TEXT")
                        .HasColumnName("parentTeachingsAnswer");

                    b.Property<string>("PaysBillsAnswer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("paysBillsAnswer");

                    b.Property<string>("SpendsOnWantsAnswer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("spendsOnWantsAnswer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fkUserId");

                    b.HasKey("UserProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MCFL.API.Models.LearningSavingsGoal", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.MoneyEntry", b =>
                {
                    b.HasOne("MCFL.API.Models.CashInCategory", "CashInCategory")
                        .WithMany()
                        .HasForeignKey("CashInCategoryId");

                    b.HasOne("MCFL.API.Models.CashOutCategory", "CashOutCategory")
                        .WithMany()
                        .HasForeignKey("CashOutCategoryId");

                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashInCategory");

                    b.Navigation("CashOutCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.MoneyFeelingSubmission", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.ParentAccessLink", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.ParentConsent", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.ParentFeedback", b =>
                {
                    b.HasOne("MCFL.API.Models.ParentAccessLink", "ParentAccessLink")
                        .WithMany()
                        .HasForeignKey("ParentAccessLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentAccessLink");
                });

            modelBuilder.Entity("MCFL.API.Models.ScenarioChoice", b =>
                {
                    b.HasOne("MCFL.API.Models.Scenario", "Scenario")
                        .WithMany("ScenarioChoices")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MCFL.API.Models.ScenarioPlay", b =>
                {
                    b.HasOne("MCFL.API.Models.ScenarioChoice", "ScenarioChoice")
                        .WithMany()
                        .HasForeignKey("ScenarioChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCFL.API.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("ScenarioChoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.UserFeedback", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.UserGameStat", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCFL.API.Models.UserLearningPreference", b =>
                {
                    b.HasOne("MCFL.API.Models.LearningTopic", "LearningTopic")
                        .WithMany("UserLearningPreferences")
                        .HasForeignKey("LearningTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MCFL.API.Models.UserProfile", "UserProfile")
                        .WithMany("UserLearningPreferences")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningTopic");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MCFL.API.Models.UserProfile", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MCFL.API.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MCFL.API.Models.LearningTopic", b =>
                {
                    b.Navigation("UserLearningPreferences");
                });

            modelBuilder.Entity("MCFL.API.Models.Scenario", b =>
                {
                    b.Navigation("ScenarioChoices");
                });

            modelBuilder.Entity("MCFL.API.Models.UserProfile", b =>
                {
                    b.Navigation("UserLearningPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
